spring:
  application:
    name: web-builder
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

server:
  port: 8080

